apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: service-match-engine
  name: loadbalancer-service-match-engine
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: service-match-engine
  type: LoadBalancer