apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: service-data-processor-function
  namespace: default
spec:
  scaleTargetRef:
    name: service-data-processor-function
  minReplicaCount: 0
  maxReplicaCount: 2
  pollingInterval: 1
  triggers:
  - type: azure-servicebus
    metadata:
      connectionFromEnv: AzureWebJobsStorage