apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileshare-nlp-models
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azurefilesharesecretnlpmodels
    secretNamespace: default
    shareName: __azurefilesharenlpmodels__
    readOnly: false