######################################################################################################
# Mongo docker-compose for local use                                                              #
######################################################################################################

version: '3.4'
services:
  mongo:
    image: 'mongo:latest'
    container_name: service-match-engine-mongo
    restart: always
    volumes:
      - service-match-engine-db:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
volumes:
  service-match-engine-db: